services:
  nextjs:
    image: node:18-alpine
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["npm", "run", "test"]


